# Machine Learning

*Лектор: Екатерина Лобачева*

*Факультет экономических наук НИУ ВШЭ, 2017-18 учебный год*

[Страница курса](http://wiki.cs.hse.ru/Машинное_обучение_(факультет_экономических_наук%29)

Семинар основан на [этом](https://github.com/esokolov/ml-course-hse/blob/master/2016-fall/seminars/sem01-tools.ipynb) ноутбуке.

# Знакомство с jupyter

Документ jupyter notebook имеет расширение `.ipynb`, состоит из множества ячеек. В ячейках можно писать программный код, делать размеченные и неразмеченные заметки. Этим функциям соответствует три типа ячеек:
    
    1. code
    2. markdown
    3. raw

Для работы с содержимым ячейки используется *режим редактирования* (*Edit mode*, включается нажатием клавиши **Enter** после выбора ячейки), а для навигации между ячейками искользуется *командный режим* (*Command mode*, включается нажатием клавиши **Esc**). 

Тип ячейки можно задать в командном режиме либо с помощью горячих клавиш (**y** to code, **m** to markdown, **r** to edit raw text), либо в меню *Cell → Cell type*. 

In [1]:
# Ячейка с кодом
a = 1

## Ячейка с размеченным текстом

После заполнения ячейки нужно нажать *Shift + Enter*, эта команда обработает содержимое ячейки: проинтерпретирует код или сверстает размеченный текст.

Ячейки с программным кодом разделяют область видимости:

In [2]:
a = 1

In [3]:
print(a)

1


# Пара слов о вёрстке 
[Здесь](https://athena.brynmawr.edu/jupyter/hub/dblank/public/Jupyter%20Notebook%20Users%20Manual.ipynb) находится <s>не</s>большая заметка о используемом языке разметки Markdown. Он позволяет:

0. Составлять упорядоченные списки
1. #Делать 
##заголовки 
###разного уровня
3. Выделять *текст* <s>при</s> **необходимости**
4. Добавлять [ссылки](http://imgs.xkcd.com/comics/the_universal_label.png)


* Составлять неупорядоченные списки

Делать вставки с помощью LaTex:
    
$
\left\{
\begin{array}{ll}
x = 16 \sin^3 (t) \\ 
y = 13 \cos (t) - 5 \cos (2t) - 2 \cos (3t) - \cos (4t) \\
t \in [0, 2 \pi]
\end{array}
\right.$

Можно также вставлять изображения:
<img src = "http://cs625727.vk.me/v625727306/3e600/rEqFs3UK3-s.jpg">

# Python

In [4]:
x = 1
y = 2
x

1

In [5]:
print("x =", x)
print("y =", y)
print("x + y =", x + y)

x = 1
y = 2
x + y = 3


In [6]:
x = x + 5
# вычислить значение выражения x + 5 
# и положить результат снова в переменную x 
x

6

In [7]:
some_list = [11, 5, 10, 101, 25]
some_list[0] # получить первый элемент списка (нумерация начинается с нуля)

11

In [8]:
some_list[-1] # получить последний элемент списка

25

In [9]:
some_list[3] = 999 # модифицировать элемент с индексом 3
some_list

[11, 5, 10, 999, 25]

In [10]:
first_list = [1, 2, 3]
second_list = [4, 5, 6]
print(first_list + second_list)

[1, 2, 3, 4, 5, 6]


In [11]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
for i in [2, 5, 7]:
    print(i**2) # перебрать все элементы списка и вывести их квадраты
print("That's all") # блок команд выделяется отступом

4
25
49
That's all


In [13]:
second_list.index(6) # найти индекс заданного элемента
# .index — это вызов метода для объекта second_list
# то есть мы говорим, что нужно искать число 6 в списке second_list

2

In [14]:
second_list.append(10) # добавить элемент
second_list

[4, 5, 6, 10]

Чтобы просмотреть список методов в Jupyter нужно набрать имя объекта (например, `second_list`), поставить точку и нажать кнопку Tab.

In [15]:
# подключение пакетов
import math
print(math.sqrt(4))

import math as mt
print(mt.sqrt(4))

from math import sqrt
print(sqrt(4))

2.0
2.0
2.0


Пошаговое выполнение Python-кода с визуализацией всего происходящего [здесь](http://pythontutor.com/visualize.html#mode=edit).

# NumPy

**NumPy** — библиотека языка Python, позволяющая [удобно] работать с многомерными массивами и матрицами, содержащая математические функции. Кроме того, NumPy позволяет векторизовать многие вычисления, имеющие место в машинном обучении. 

 - [numpy](http://www.numpy.org)
 - [numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/)
 - [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)

In [16]:
import numpy as np
# так подключаются дополнительные пакеты
# в данном случае мы подключили пакет numpy и сказали, что все функции из
# этого пакета будут вызываться с префиксом np.

Основным типом данных NumPy является многомерный массив элементов одного типа — [numpy.ndarray](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.array.html). Каждый подобный массив имеет несколько *измерений* или *осей* — в частности, вектор (в классическом понимании) является одномерным массивом и имеет 1 ось, матрица является двумерным массивом и имеет 2 оси и т.д.

In [17]:
vec = np.array([1, 2, 3])
vec.ndim # количество осей

1

In [18]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.ndim

2

Чтобы узнать длину массива по каждой из осей, можно воспользоваться атрибутом shape:

In [19]:
vec.shape

(3,)

Чтобы узнать тип элементов и их размер в байтах:

In [20]:
mat.dtype.name

'int64'

In [21]:
mat.itemsize

8

## Создание массивов

* Передать итерируемый объект в качестве параметра функции array (можно также явно указать тип элементов):

In [22]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [23]:
A = np.array([1, 2, 3], dtype = float)
A

array([ 1.,  2.,  3.])

In [24]:
B = np.array([(1, 2, 3), (4, 5, 6)])
B

array([[1, 2, 3],
       [4, 5, 6]])

* Создание массивов специального вида при помощи функций zeros, ones, empty, identity:

In [25]:
np.zeros((3,))

array([ 0.,  0.,  0.])

In [26]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [27]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [28]:
np.empty((2, 5))

array([[  2.31584178e+077,   4.32971660e-311,   2.37663529e-312,
          2.56761491e-312,   8.48798317e-313],
       [  9.33678148e-313,   1.12465777e-312,   8.70018274e-313,
          0.00000000e+000,   6.95335581e-309]])

Обратите внимание, что содержимое массива, созданного при помощи функции empty, **не инициализируется**, то есть в качестве значений он **может содержать "мусор"**.

* Создание последовательностей при помощи функций arange (в качестве парметров принимает левую и правую границы последовательности и **шаг**) и linspace (принимает левую и правую границы и **количество элементов**):

In [29]:
np.arange(2, 20, 3) # аналогично стандартной функции range python, правая граница не включается

array([ 2,  5,  8, 11, 14, 17])

In [30]:
np.arange(2.5, 8.7, 0.9) # но может работать и с вещественными числами

array([ 2.5,  3.4,  4.3,  5.2,  6.1,  7. ,  7.9])

In [31]:
np.linspace(2, 18, 14) # правая граница включается (по умолчанию)

array([  2.        ,   3.23076923,   4.46153846,   5.69230769,
         6.92307692,   8.15384615,   9.38461538,  10.61538462,
        11.84615385,  13.07692308,  14.30769231,  15.53846154,
        16.76923077,  18.        ])

* Для изменения размеров существующего массива можно воспользоваться функцией reshape (при этом количество элементов должно оставаться неизменным):

In [32]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Вместо значения длины массива по одному из измерений можно указать -1 — в этом случае значение будет рассчитано автоматически:

In [33]:
np.arange(8).reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

* Транспонирование существующего массива:

In [34]:
C = np.arange(6).reshape(2, -1)
C

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
C.T

array([[0, 3],
       [1, 4],
       [2, 5]])

* Объединение существующих массивов по заданной оси:

In [36]:
A = np.arange(6).reshape(2, -1)
np.hstack((A, A**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [37]:
np.vstack((A, A**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [38]:
np.concatenate((A, A**2), axis = 1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

* Повторение существующего массива

In [39]:
a = np.arange(3)
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [40]:
np.tile(a, (4, 1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

## Базовые операции

* Базовые арифметические операции над массивами выполняются поэлементно:

In [41]:
A = np.arange(9).reshape(3, 3)
B = np.arange(1, 10).reshape(3, 3)

In [42]:
print(A)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
A + B

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [44]:
A * 1.0 / B

array([[ 0.        ,  0.5       ,  0.66666667],
       [ 0.75      ,  0.8       ,  0.83333333],
       [ 0.85714286,  0.875     ,  0.88888889]])

In [45]:
A + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
3 * A

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [47]:
A ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

Отдельно обратим внимание на то, что умножение массивов также является **поэлементным**, а не матричным:

In [48]:
A * B

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

Для выполнения матричного умножения необходимо использовать функцию dot или `@` (в Python 3):

In [49]:
A.dot(B)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [50]:
A @ B

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

Поскольку операции выполняются поэлементно, операнды бинарных операций должны иметь одинаковый размер. Тем не менее, операция может быть корректно выполнена, если размеры операндов таковы, что они могут быть расширены до одинаковых размеров. Данная возможность называется [broadcasting](http://www.scipy-lectures.org/intro/numpy/operations.html#broadcasting):
<img src = "http://www.scipy-lectures.org/_images/numpy_broadcasting.png">

In [51]:
np.tile(np.arange(0, 40, 10), (3, 1)).T + np.array([0, 1, 2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

* Универсальные функции (sin, cos, exp и т.д.) также применяются поэлементно:

In [52]:
np.exp(A)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00],
       [  2.00855369e+01,   5.45981500e+01,   1.48413159e+02],
       [  4.03428793e+02,   1.09663316e+03,   2.98095799e+03]])

* Некоторые операции над массивами (например, вычисления минимума, максимума, суммы элементов) выполняются над всеми элементами вне зависимости от формы массива, однако при указании оси выполняются вдоль нее (например, для нахождения максимума каждой строки или каждого столбца):

In [53]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
A.min()

0

In [55]:
A.max(axis = 0)

array([6, 7, 8])

In [56]:
A.sum(axis = 1)

array([ 3, 12, 21])

## Индексация

Для доступа к элементам может использоваться [много различных способов](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html), рассмотрим основные.

* Для индексации могут использоваться конкретные значения индексов и срезы (slice), как и в стандартных типах Python. Для многомерных массивов индексы для различных осей разделяются запятой. Если для многомерного массива указаны индексы не для всех измерений, недостающие заполняются полным срезом (:).

In [57]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a[2:5]

array([2, 3, 4])

In [59]:
a[3:8:2]

array([3, 5, 7])

In [60]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [61]:
A[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [62]:
A[:, 2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [63]:
A[2:4, 2:4]

array([[20, 21],
       [29, 30]])

In [64]:
A[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

* Также может использоваться индексация при помощи списков индексов (по каждой из осей):

In [65]:
A = np.arange(81).reshape(9, -1)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [66]:
A[[2, 4, 5], [0, 1, 3]]

array([18, 37, 48])

* Может также применяться логическая индексация (при помощи логических массивов):

In [67]:
A = np.arange(11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
A[A % 5 != 3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [69]:
A[np.logical_and(A != 7, A % 5 != 3)] # также можно использовать логические операции

array([ 0,  1,  2,  4,  5,  6,  9, 10])

## Примеры

In [70]:
A = np.arange(120).reshape(10, -1)
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

1. Выбрать все четные строки матрицы A.
2. Составить одномерный массив из всех не делящихся на 3 элементов нечетных столбцов А.
3. Посчитать сумму диагональных элементов A.

In [71]:
# Your code here

## Зачем?

Зачем необходимо использовать NumPy, если существуют стандартные списки/кортежи и циклы?

Причина заключается в скорости работы. Попробуем посчитать сумму поэлементых произведений 2 больших векторов:

In [72]:
import time

A_quick_arr = np.random.normal(size = (1000000,))
B_quick_arr = np.random.normal(size = (1000000,))

A_slow_list, B_slow_list = list(A_quick_arr), list(B_quick_arr)

In [73]:
start = time.clock()
ans = 0
for i in range(len(A_slow_list)):
    ans += A_slow_list[i] * B_slow_list[i]
print(time.clock() - start) # время выполнения в секундах

0.6052809999999997


In [74]:
start = time.clock()
ans = sum([A_slow_list[i] * B_slow_list[i] for i in range(1000000)])
print(time.clock() - start)

0.540527


In [75]:
start = time.clock()
ans = np.sum(A_quick_arr * B_quick_arr)
print(time.clock() - start)

0.020347000000000115


In [76]:
start = time.clock()
ans = A_quick_arr.dot(B_quick_arr)
print(time.clock() - start)

0.0028719999999999857


# Pandas

<img src = "http://bconnelly.net/assets/img/pandas1.png">

In [77]:
import pandas as pd
%matplotlib inline

**Pandas** (Python Data Analysis Library) — библиотека языка Python для [удобных] обработки и анализа данных.


Рассмотрим данную библиотеку на примере [данных](https://www.kaggle.com/c/titanic/data) [соревнования](https://www.kaggle.com/c/titanic) о предсказании судьбы пассажиров лайнера "Титаник". Имеется некоторая информация о пассажирах, по которой необходимо предсказать выживаемость каждого из них.
* Какого типа данная задача?
* Что является объектами?
* Что является ответами?
* Какие могут быть признаки? Какие у них типы?

Загрузка данных в **pandas** происходит в специальный объект типа **DataFrame**:

In [78]:
pass_data = pd.read_csv('titanic.csv')
pass_data

FileNotFoundError: File b'titanic.csv' does not exist

Как видно, данные представляют из себя таблицу, где строка — объект, столбец — признак. Для экономии места можно выводить заданное количество первых строк объекта при помощи метода head():

In [ ]:
pass_data.head(3)

Посмотрим на признаки:

In [ ]:
pass_data.columns

По данным можно индексироваться при помощи номеров строк/столбцов или названий признаков:

In [ ]:
pass_data[2:5]

In [ ]:
pass_data.iloc[1:5, 1:3]

In [ ]:
pass_data['name'].head()

In [ ]:
pass_data[['name', 'sex', 'parch']].head()

Также действует и логическая индексация, которая позволяет рассматривать определенные группы объектов:

In [ ]:
pass_data[pass_data['sex'] == 'female'].head() # женщины на борту

In [ ]:
# женщины старше 60 и мужчины на борту
pass_data[(pass_data['sex'] == 'female') & (pass_data['age'] >= 60) | (pass_data['sex'] == 'male')].head()

#### Пример
Посмотрим, сколько на борту было относительно молодых женщин, путешествующих в одиночку. Скорее всего, довольно мало, потому что в такое длительное путешествие молодых девушек одних не отпустили бы опекающие родственники.

In [ ]:
pass_data[(pass_data.sex == 'female') & 
          (pass_data.age > 18) & 
          (pass_data.age < 25) & 
          (pass_data.sibsp == 0) &
          (pass_data.parch == 0)].shape

Кроме того, для заданного признака можно построить гистограмму:

In [ ]:
pass_data.age.hist(bins = 30)

## Редактирование DataFrame

* Переименование признаков

In [ ]:
pass_data.rename(columns={'sex': 'Sex'}, inplace=True)
pass_data.head()

* Применение преобразования к существующему признаку. Например, выделим фамилию:

In [ ]:
def get_last_name(name):
    return name.split(',')[0].strip()

last_names = pass_data['name'].apply(get_last_name)
last_names.head()

* Добавление признака

In [ ]:
pass_data['Last_name'] = last_names
pass_data.head()

* Удаление признака

In [ ]:
pass_data.drop('Last_name', axis=1, inplace=True)
pass_data.head()

* Работа с пропущенными данными

Методы isnull() и notnull() позволяют получить бинарный массив, отражающий отсутствие или наличие данных для каждого из объектов соответственно:

In [ ]:
pass_data['boat'].isnull().head()

In [ ]:
pass_data[pass_data['boat'].notnull()].head() # пассажиры с известным номером шлюпки эвакуации

* Сортировка объектов/признаков

In [ ]:
pass_data.sort_values(by=['pclass', 'fare'], ascending=True).head()

In [ ]:
pass_data.sort_values(by=['pclass', 'fare'], ascending=[True, False]).head()

## Группировка данных

Группировка при помощи метода groupby позволяет объединять данные в группы по одному или нескольким признакам и считать по ним общую статистику.

In [ ]:
pass_data.groupby('Sex') # разбиение всех объектов на 2 группы по полу

In [ ]:
pass_data.groupby('Sex')['pclass'].value_counts()

In [ ]:
pass_data.groupby('pclass')['fare'].describe()

In [ ]:
pass_data.groupby('Sex')['age'].mean() # средний возраст для пассажиров каждого из полов

Как известно, в первую очередь спасали женщин и детей в порядке повышения номера класса, в связи с этим доля выживших женщин, вероятно, будет выше, чем доля выживших мужчин. Проверим:

In [ ]:
pass_data.groupby('Sex')['survived'].mean()

Аналогично для пассажиров различных классов:

In [ ]:
pass_data.groupby('pclass')['survived'].mean()

Рассмотренные выше статистические данные могут быть рассмотрены и в виде стандартного DataFrame:

In [ ]:
pass_data.groupby('Sex', as_index=False)['survived'].mean()

## Сохранение данных

Также данные можно сохранить в файл:

In [ ]:
pass_data.to_csv('titanic_2.csv', index=False)

# Matplotlib

* [matplotlib](http://matplotlib.org)
* [matplotlib - 2D and 3D plotting in Python](http://nbviewer.jupyter.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-4-Matplotlib.ipynb)
* [visualization in pandas](http://pandas.pydata.org/pandas-docs/stable/visualization.html)

**Matplotlib** — библиотека языка Python, используемая для визуализации.

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
x = np.linspace(1, 10, 20)

Для построения графиков в matplotlib используются фигуры и заданные для них оси, что довольно удобно в случае, когда необходимо строить несколько графиков или их расположение нестандартное.

In [ ]:
fig = plt.figure(figsize=(10, 6))

axes = fig.add_axes([0.1, 0.1, 0.8, 0.8])

axes.plot(x, x ** 2, 'r')
axes.plot(x, x ** 3, 'b*--')

axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title')
axes.legend([r'$x^2$', 'x^3'], loc = 0)

In [ ]:
fig = plt.figure(figsize=(10, 6))

axes = fig.add_axes([0.1, 0.1, 0.8, 0.8])

axes.scatter(x, x ** 2, color='red', marker='*', s=80)
axes.scatter(x, x ** 3)

axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title')

Matplotlib позволяет настраивать многие детали создаваемых графиков:

In [ ]:
fig = plt.figure(figsize=(10, 6))

axes = fig.add_axes([0.1, 0.1, 0.8, 0.8])

axes.plot(x, x ** 2, 'r^-', label = r'$y = x^2$', markersize=8, markerfacecolor="yellow", 
          markeredgewidth=1, markeredgecolor="green")
axes.plot(x, x ** 3, 'b*--', label = r'$y = x^3$', alpha = 0.5)

axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title')
axes.legend(loc = 0, fontsize = 18)

Как было упомянуто, matplotlib предоставляет определенную свободу в расположении подграфиков:

In [ ]:
fig = plt.figure()

axes1 = fig.add_axes([0.1, 0.1, 0.8, 0.8]) # main axes
axes2 = fig.add_axes([0.2, 0.5, 0.4, 0.3]) # inset axes

# main figure
axes1.plot(x, x ** 2, 'r')
axes1.set_xlabel('x')
axes1.set_ylabel('y')
axes1.set_title('title')

# insert
axes2.plot(x ** 2, x, 'g')
axes2.set_xlabel('y')
axes2.set_ylabel('x')
axes2.set_title('insert title')

Впрочем, можно использовать и одну из классических конфигураций:

In [ ]:
fig, axes = plt.subplots(nrows=1, ncols=3, figsize = (16, 5))

for pow_num, ax in enumerate(axes):
    ax.plot(x, x ** (pow_num + 1), 'r')
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_title(r'$y = x^' + str(pow_num + 1)+ r'$', fontsize = 18)
fig.tight_layout() # борьба с пересечением подграфиков

Получившийся график можно сохранить в файл:

In [ ]:
fig.savefig("pows.png", dpi=200)

Matplotlib также позволяет строить surface plot, используя значения функции в узлах сетки:

In [ ]:
alpha = 0.7
phi_ext = 2 * np.pi * 0.5

def flux_qubit_potential(phi_m, phi_p):
    return 2 + alpha - 2 * np.cos(phi_p) * np.cos(phi_m) - alpha * np.cos(phi_ext - 2*phi_p)

phi_m = np.linspace(0, 2*np.pi, 100)
phi_p = np.linspace(0, 2*np.pi, 100)
X,Y = np.meshgrid(phi_p, phi_m)
Z = flux_qubit_potential(X, Y).T

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(14,6))

ax = fig.add_subplot(111, projection='3d')

p = ax.plot_surface(X, Y, Z, rstride=4, cstride=4, linewidth=0, cmap='jet')

Кроме того, можно строить более детализированные гистограммы по сравнению с теми, что мы рассмотрели ранее:

In [ ]:
fig = plt.figure()
axes = fig.add_axes([0.0, 0.0, 1.0, 1.0])
bins = 20
index = np.arange(bins)
axes.hist(pass_data[pass_data['Sex'] == 'male']['age'].dropna(), bins=bins, alpha=0.6, label='male')
axes.hist(pass_data[pass_data['Sex'] == 'female']['age'].dropna(), bins=bins, alpha=0.6, label='female')

axes.legend()
axes.set_xlabel('Age', fontsize=18)
axes.set_ylabel('Count', fontsize=18)
axes.set_title('Age by gender', fontsize=18)

Заметим также, что Matplotlib позволяет использовать многие другие типы визуализации, подробнее про них можно почитать, например, [здесь](http://matplotlib.org/gallery.html) или [здесь](http://nbviewer.jupyter.org/github/jrjohansson/scientific-python-lectures/blob/master/Lecture-4-Matplotlib.ipynb).