In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [32]:
def gradient_descent(func, grad, w_0 = None, nu_0 = 0.001, max_iter = 1000):
    if w_0 is None:
        w_t = np.zeros(3)
    else:
        w_t = w_0
    
    for i in range(max_iter):
        grad_t = grad(w_t)
        
        if np.linalg.norm(grad_t) < 1e-5:
            break
            
        w_t = w_t - nu_0 * grad_t
    
    return w_t

In [5]:
def func(X, y, w):
    e = y - X.dot(w)
    return (e).dot(e)

In [24]:
def grad(X, y, w):
    return -2 * X.T.dot(y - X.dot(w))

In [25]:
from sklearn.datasets import make_regression

In [26]:
X, y = make_regression(n_features=3)

In [33]:
result = gradient_descent(lambda b: func(X,y,b), lambda b: grad(X, y, b))

In [34]:
result

array([ 80.58628711,  50.72117069,  23.50051296])

In [35]:
g = lambda b: grad(X, y, b)

In [37]:
np.linalg.norm(g(result))

9.0616360749912979e-06

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
ref = LinearRegression()

In [40]:
ref.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [41]:
ref.coef_

array([ 80.58628716,  50.72117067,  23.50051294])

In [44]:
ref.predict(X[:2])

array([ 87.95090259,  35.11646345])